name: Build

on:
  push:
    paths:
      - "**.gradle"
      - "**.properties"
      - "**.java"
      - "**.toml"
      - "**.xml"
      - ".github/workflows/*.yml"
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build (${{ matrix.os }}, JDK ${{ matrix.java }})
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push'
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        java:
          - 22
          - 25
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: JDK Setup
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v6

      - name: Build with Gradle Wrapper
        run: ./gradlew build -PskipSpotless

      - name: Publish Test Results
        if: ${{ !cancelled() }}
        uses: dorny/test-reporter@v3
        with:
          name: JUnit (${{ matrix.os }}, JDK ${{ matrix.java }})
          reporter: java-junit
          path: '**/test-results/**/*.xml'

      - name: Code Style Validation
        if: matrix.os == 'ubuntu-latest' && matrix.java == '22'
        run: ./gradlew spotlessCheck
