name: Build

on:
  push:
    paths:
      - "**.gradle"
      - "**.properties"
      - "**.java"
      - "**.toml"
      - "**.xml"
      - ".github/workflows/*.yml"
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
     - name: Checkout
       uses: actions/checkout@v6
       with:
         fetch-depth: 0

     - name: JDK Setup
       uses: actions/setup-java@v5
       with:
         distribution: temurin
         java-version: 23

     - name: Setup Gradle
       uses: gradle/actions/setup-gradle@v5

     - name: Gradle Wrapper Validation
       uses: gradle/actions/wrapper-validation@v5

     - name: Build with Gradle Wrapper
       run: ./gradlew build -PskipSpotless

     - name: Publish Test Results
       uses: dorny/test-reporter@v2
       with:
         name: JUnit test results
         reporter: java-junit
         path: '**/test-results/**/*.xml'

     - name: Code Style Validation
       run: ./gradlew spotlessCheck
